# Generated by Django 4.2.16 on 2024-09-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicpostsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text',
        ),
    ]
